# Generated by Django 4.0.6 on 2022-12-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatModel',
        ),
    ]
