# Generated by Django 4.0.6 on 2022-10-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('team_background', models.TextField()),
                ('company_products', models.TextField()),
                ('solve', models.TextField()),
                ('solution', models.TextField()),
                ('incubation_needed', models.CharField(max_length=100)),
                ('business_proposal', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
