# Generated by Django 4.0.6 on 2022-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incub', '0003_booking_allotted_booking_approved_booking_declined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
