# Generated by Django 4.0.6 on 2022-10-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incub', '0004_booking_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(unique=True)),
                ('is_booked', models.BooleanField(blank=True, default=False, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incub.booking')),
            ],
        ),
    ]
